version: "3"
services:
  mysql:
    image: mysql:8.0.31
    volumes:
      - /data/mysql/script:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=111111
      - MYSQL_DATABASE=doris-test
    command:
      --character-set-server=utf8
    hostname: mysql
    ports:
      - "3306:3306"
  jobmanager:
    image: registry.cn-hangzhou.aliyuncs.com/smithone/flink:1.17-scala_2.12
    expose:
      - "6123"
    ports:
      - "8081:8081"
    volumes:
      - /root/doris/flink-doris-connector-1.17-1.6.2.jar:/opt/flink/lib/flink-doris-connector-1.17-1.6.2.jar
      - /root/doris/flink-sql-connector-mysql-cdc-2.4.2.jar:/opt/flink/lib/flink-sql-connector-mysql-cdc-2.4.2.jar
      - /root/doris/flink-sql-connector-sqlserver-cdc-2.4.2.jar:/opt/flink/lib/flink-sql-connector-sqlserver-cdc-2.4.2.jar
      - /data/flink_jobmanager/log:/opt/flink/log
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
  taskmanager:
    image: registry.cn-hangzhou.aliyuncs.com/smithone/flink:1.17-scala_2.12
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    volumes:
      - /root/doris/flink-doris-connector-1.17-1.6.2.jar:/opt/flink/lib/flink-doris-connector-1.17-1.6.2.jar
      - /root/doris/flink-sql-connector-mysql-cdc-2.4.2.jar:/opt/flink/lib/flink-sql-connector-mysql-cdc-2.4.2.jar
      - /data/flink_taskmanager/log:/opt/flink/log
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
  doris:
    image: registry.cn-hangzhou.aliyuncs.com/freeoneplus/doris:2.1.4-all
    hostname: doris
    ports:
      - "8030:8030"
      - "9030:9030"
      - "8040:8040"
    volumes:
      - /data/fe/doris-meta:/opt/apache-doris/fe/doris-meta
      - /data/fe/log:/opt/apache-doris/fe/log
      - /data/be/storage:/opt/apache-doris/be/storage
      - /data/be/log:/opt/apache-doris/be/log
    network_mode: host
  superset:
    image: selectdb/superset_3.0.1-cloud_3.0.3:latest
    user: "root"
    environment:
      - SUPERSET_SECRET_KEY="doris"
    command:
      - "sh"
      - -c 
      - |
          superset db upgrade
          superset fab create-admin --username admin --password doris --firstname Superset --lastname Admin --email admin@superset.com
          superset init
          /bin/sh -c /usr/bin/run-server.sh 
    ports:
      - "8088:8088"
    restart: on-failure
    network_mode: host

